name: CI-Polaris 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: '**' #[ main, master, develop, stage, release ]  
jobs:
  polaris-scan:
    runs-on: [ ubuntu-latest ]
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ vars.POLARIS_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_POLARIS_APPLICATION_NAME: RAF-ACME_Labs
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
      BRIDGE_GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRIDGE_GITHUB_REPOSITORY_OWNER_NAME: ${{ github.repository_owner }}
      BRIDGE_GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      BRIDGE_GITHUB_REPOSITORY_BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: microsoft
          cache: maven
      - name: Polaris Full Scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        with:
          polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
          polaris_application_name: RAF-ACME_Labs
          polaris_project_name: ${{ github.event.repository.name }}
          polaris_assessment_types: "SAST"
          # polaris_waitForScan: false  # Used to support the async mode
          # project_directory: ${{ vars.PROJECT_DIRECTORY }}
          ### Uncomment below configuration for source code upload 
          # polaris_assessment_mode: "SOURCE_UPLOAD"
          # project_source_archive: ${{ vars.PROJECT_SOURCE_ARCHIVE }}
          # project_source_excludes: ${{ vars.PROJECT_SOURCE_EXCLUDES }} # Accepts Multiple Values
          # project_source_preserveSymLinks: true
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
          ### SARIF report generation and upload to GitHub Adavanced Security Tab: Uncomment below to enable
          #polaris_reports_sarif_create: true  
          #polaris_reports_sarif_file_path: '/Users/tmp/report.sarif.json' # File path (including file name) where SARIF report is created.
          #polaris_reports_sarif_severities: "CRITICAL,HIGH,MEDIUM,LOW"
          #polaris_reports_sarif_groupSCAIssues: true 
          #polaris_reports_sarif_issue_types: 'SCA, SAST' 
          #polaris_upload_sarif_report: true 
          #github_token: ${{ secrets.GITHUB_TOKEN }} # Required when polaris_upload_sarif_report is set as true
          ### Signature scan
          #polaris_test_sca_type: "SCA-SIGNATURE"
          ### Uncomment below to add arbitrary CL parameters
          # blackduck_search_depth: 2
          # blackduck_args: '--detect.diagnostic=true'
          # blackduck_config_path: '/Users/Config/application.properties'
          # coverity_build_command: mvn clean install
          # coverity_clean_command: mvn clean
          # coverity_config_path: /Users/Config/coverity.yml
          # coverity_args: --config-override capture.build.build-command=mvn install
      - name: Polaris PR Scan
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          curl -fLsS -o bridge.zip ${{ vars.BRIDGECLI_LINUX64 }} && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
          ${{ runner.temp }}/bridge-cli-bundle-linux64/bridge-cli --stage polaris \
            polaris.prcomment.enabled='true' \
            polaris.branch.parent.name=${{ github.event.base_ref }} \
            github.repository.pull.number=${{ github.event.number }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
        #if: ${{ github.event_name == 'pull_request' }}
        #uses: blackduck-inc/black-duck-security-scan@v2.0.0
        #with:
        #  polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        #  polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
        #  polaris_application_name: RAF-ACME_Labs
        #  polaris_project_name: ${{ github.event.repository.name }}
        #  polaris_assessment_types: "SAST"
          # project_directory: ${{ vars.PROJECT_DIRECTORY }}
          ### Uncomment below configuration for source code upload 
          # polaris_assessment_mode: "SOURCE_UPLOAD"
          # project_source_archive: ${{ vars.PROJECT_SOURCE_ARCHIVE }}
          # project_source_excludes: ${{ vars.PROJECT_SOURCE_EXCLUDES }} # Accepts Multiple Values
          # project_source_preserveSymLinks: true
          ### Below configuration is used to enable feedback from Polaris security testing as pull request comment
        #  polaris_prComment_enabled: true  
          # Mandatory when polaris_prComment_enabled is set to 'true'
          ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
          # include_diagnostics: true
