# example pipeline for Coverity scans using the Synopsys Security Scan extension for ADO
# https://marketplace.visualstudio.com/items?itemName=synopsys-security-scan.synopsys-security-scan
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: poc329.coverity.synopsys.com

steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'

- task: SynopsysSecurityScan@1
  displayName: 'Coverity Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    scanType: coverity
    bridge_coverity_connect_url: '$(COVERITY_URL)'
    bridge_coverity_connect_user_name: '$(COV_USER)'
    bridge_coverity_connect_user_password: '$(COVERITY_PASSPHRASE)'
    bridge_coverity_connect_project_name: '$(Build.Repository.Name)'
    bridge_coverity_connect_stream_name: '$(Build.Repository.Name)-$(Build.SourceBranchName)'
    bridge_coverity_connect_policy_view: 'Outstanding Issues'

- task: SynopsysSecurityScan@1
  displayName: 'Coverity PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  inputs:
    scanType: coverity
    bridge_coverity_connect_url: '$(COVERITY_URL)'
    bridge_coverity_connect_user_name: '$(COV_USER)'
    bridge_coverity_connect_user_password: '$(COVERITY_PASSPHRASE)'
    bridge_coverity_connect_project_name: '$(Build.Repository.Name)'
    bridge_coverity_connect_stream_name: '$(Build.Repository.Name)-$(System.PullRequest.targetBranchName)'
    bridge_coverity_automation_prcomment: true
    azure_token: $(System.AccessToken)

- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'
